### ISSUE TITLE
Incorrect `gmres`?

### ISSUE THREAD

**Issue by panlanfeng** [JuliaMath/IterativeSolvers.jl#109]
In the following example
```julia
import IterativeSolvers
n=30;
A = randn(n,n); A= A.+A'; 
x = rand(n);
b = A*x; 
A*IterativeSolvers.gmres(A, b) .- b
```
It only work for `n` less than 20. This is the case for both v0.2.2 and master.

Am I using it the wrong way?

**Comment by panlanfeng** [comment]
I see. It is correct if I set `restart=length(b)+1`.
So the problem should be the default value of `restart` is too small.
For reference, the R package `pracma` provides the same function and its default `restart` is `length(b)+1`.

**Comment by haampie** [comment]
You're completely right, there is a bug in the current GMRES implementation where the best approximation is not incremented at restart, but overwritten. Let me write a one character PR for this ;)

**Comment by haampie** [comment]
This can be closed. Fixed by https://github.com/JuliaMath/IterativeSolvers.jl/pull/119/commits/cd2ad63d91148f4ae679ecd4fcafb6f01d796908
