### ISSUE TITLE
cg returns incorrect result?

### ISSUE THREAD

**Issue by memoiry** [JuliaMath/IterativeSolvers.jl#112]
Hi all

I'm trying to use this package, and below is my experiments

```julia
using IterativeSolvers
julia> A = rand(10,10);

julia> b = rand(10);

julia> x = cg(A,b)[1];

julia> A*x-b
10-element Array{Float64,1}:
 -28.5586
 -86.5707
 -55.2936
 -85.9302
 -63.0426
 -26.0243
 -86.1318
 -26.6518
 -69.1788
  27.4126
```

Is there anything wrong? the result is a little confusing, it should be nearly zero I think. any explanation will be helpful, thanks!

**Comment by KristofferC** [comment]
What are the requirements on A for the conjugate gradient method to converge?

**Comment by ChrisRackauckas** [comment]
>What are the requirements on A for the conjugate gradient method to converge?

Symmetric positive definite. That should probably be added to the docs. For random, you'll want something more general like `gmres`.

```julia
A = rand(10,10)
b = rand(10)
using IterativeSolvers
x = gmres(A,b)
A*x - b
```

**Comment by KristofferC** [comment]
... I didn't ask the question because I wondered about the answer. It was for the OP.

**Comment by memoiry** [comment]
@KristofferC @ChrisRackauckas Thanks for the kindly explanation.
