### ISSUE TITLE
Make return values useful

### ISSUE THREAD

**Issue by haampie** [JuliaMath/IterativeSolvers.jl#136]
At the moment we return either all logs or none. In most practical cases you would not necessarily need the residual norm in each iteration, but you do need to know whether the method is converged. And if the method is not converged, it might be useful to know why (breakdown of the method, stagnation, too few iterations). These reasons are of course specific to the method.

Should we maybe always return a pair `(solution, convergence_history)` even if `log = false`? Is the main rational behind having `log = false` that we don't have to store a vector of residual norms? Should we maybe differentiate between logging that is done in each iteration and logging at the end?

**Comment by ChrisRackauckas** [comment]
IMO, return a type with an array overload and these changes aren't breaking. Otherwise these types of API changes are always rough and you have to be extra careful before changing.

**Comment by haampie** [comment]
Hm, this can be closed in favour of #6
