### ISSUE TITLE
Lanczos implementation not useful in practice

### ISSUE THREAD

**Issue by haampie** [JuliaMath/IterativeSolvers.jl#144]
There are multiple issues with the current implementation of the Lanczos method for the Hermetian eigenvalue problem, which makes it actually unusable in practice:

1. No re-orthogonalization: due to loss of orthogonality of the Krylov basis vectors, eigenvalues are detected multiple times (and therefore some aren't found):

```
> srand(1)
> A = rand(100, 100)
> A = A + A'
> eigvals(A)[end - 10 : end]
11-element Array{Float64,1}:
   5.74519
   5.88254
   6.3581
   6.40497
   6.56969
   6.83121
   7.01442
   7.21099
   7.48439
   7.58956
 100.818
> eiglancz(A)[end - 10 : end]
11-element Array{Float64,1}:
   7.48439
   7.58956
 100.818
 100.818
 100.818
 100.818
 100.818
 100.818
 100.818
 100.818
 100.818
```
2. The `maxiter` keyword is not passed on to the actual method
3. The stopping criterion is not useful: often you want to compute a couple eigenvalues near a target, and while other Ritz values aren't converged, the ones near the target may have. The stopping target should incorporate that.
4. The current implementation cannot deal with multiple eigenvalues: only one vector in the null space of (A - sI) is found, while the dimension can be larger than 1.

**Comment by andreasnoack** [comment]
Fixed by #146
