### ISSUE TITLE
gmres returns NaNs

### ISSUE THREAD

**Issue by omalled** [JuliaMath/IterativeSolvers.jl#155]
It seems that `gmres(A, zeros(n))` always returns a vector full of NaNs. For example,

```
all(isnan(IterativeSolvers.gmres(eye(2), zeros(2))))#evaluates to true
all(isnan(IterativeSolvers.gmres(randn(100, 100), zeros(100))))#evaluates to true in every case I tried
```

It also occurred for me when `A` is a sparse matrix arising from a discretization of a PDE.

**Comment by haampie** [comment]
The current master branch of IterativeSolvers does not have this behaviour, so this is automatically fixed in the next release.

```julia
> IterativeSolvers.gmres(eye(2), zeros(2))
2-element Array{Float64,1}:
 0.0
 0.0
```

```julia
> IterativeSolvers.gmres!(rand(2), eye(2), zeros(2))
2-element Array{Float64,1}:
 -5.55112e-17
 -2.08167e-17
```
