### ISSUE TITLE
Reducing memory allocation

### ISSUE THREAD

**Issue by Jutho** [JuliaMath/IterativeSolvers.jl#16]
I completed a first browsing through the code of this package. I would like to comment that, if speed/efficiency is going to be high on the focus list, excessive memory allocation should be avoided. One example is the orthogonalize routine, which will be the backbone of many solvers and will be called many times:

``` julia
    elseif method == :ModifiedGramSchmidt || method== :Householder
        #The numerical equivalence of ModifiedGramSchmidt and Householder was
        #established in doi:10.1137/0613015
        cs = zeros(T, p)
        for (i, e) in enumerate(Kk)
            cs[i] = dot(v, e)
            v-= cs[i] * e
        end
    else
```

I strongly believe the `v=-cs[i]*e` line should call Base.LinAlg.BLAS.axpy!
This will of course modify v in place, such that `orthogonalize` should become `orthogonalize!`, which I think is fine. I would be happy to change this if everybody agrees.

On a side note, even though ModifiedGramSchmidt is numerically equivalent to some form of HouseHolder orthogonalization on matrix stacked with zeros on top of it (which is useful to get good error bounds and get better insights in how to modify existing algorithms), this doesn't imply that it is equivalent to HouseHolder applied to the original matrix, nor that things like a second reorthogonalization round in MGS is useless. (Although I certainly agree that MGS is sufficient for many algorithms which only use small Krylov subspaces).

**Comment by haampie** [comment]
Orthogonalization doesn't copy anymore, so we can close this issue. See `src/orthogonalize.jl`
