### ISSUE TITLE
preconditioned CG for dummies

### ISSUE THREAD

**Issue by randomjc** [JuliaMath/IterativeSolvers.jl#164]
Hi,

I would like to solve a linear system using the preconditioned CG method. I have a good conditioner at hand, a lower triangular matrix L such that L * L' is close to the matrix of my system, but I can't understand how I can pass this information to the `cg` function. I saw that there is the `Pl` keyword which is related to having a left preconditioner, but I can't figure out how to use this. I am sorry to ask so elementary questions, but I have been going around for hours trying to figure this out and I'm still in the dark. I just need to see what command I am supposed to type assuming that I want to solve for x in A*x = b with the preconditioner L. Thanks in advance for your help.

**Comment by randomjc** [comment]
To be more precise, I don't understand why when I type

```
cg(A, b ; tol = 0.1, maxiter = 10)
```

everything works fine, but when I type any of
```
cg(A, b ; plot = false)
cg(A, b ; log = false)
cg(A, b ; Pl = 1)
```
I get 
```
ERROR: unrecognized keyword argument "plot"
```
or similarly with `log` or `Pl`.

**Comment by haampie** [comment]
There are multiple things going on here. First, the `plot` keyword has been removed in version 0.4 of IterativeSolvers. Secondly `log = false` is the default value, so you could just remove that.

About preconditioners in general: we assume you provide a method `A_ldiv_B!` for your preconditioner that basically computes `L \ x` in-place. Something along the lines of this might work:

```julia
import Base.LinAlg.A_ldiv_B!

struct MyPreconditionerType{matT}
    lower::matT
end

MyPreconditionerType(L::SparseMatrixCSC) = MyPreconditionerType(LowerTriangular(L))

# Performs x <- L' \ (L \ x) in-place with backward & forward substitutions
A_ldiv_B!(P::MyPreconditionerType, x) = Ac_ldiv_B!(P.lower, A_ldiv_B!(P.lower), x))
A_ldiv_B!(y, P::MyPreconditionerType, x) = A_ldiv_B!(P, copy!(y, x))

# ...

P = MyPreconditionerType(L)
x, history = cg(A, b, Pl = P, maxiter = 100, log = true)
```

**Comment by randomjc** [comment]
Ok, your first comment about versions is already very useful. One of the reasons I was so confused is that I was reading the documentation [here](https://juliamath.github.io/IterativeSolvers.jl/latest/), and if you go to the paragraph describing the `cg` method and follow the link to the source, you are linked to a [much older](https://github.com/JuliaMath/IterativeSolvers.jl/tree/4584403fd7dd2367dd3044262a4f417642517be3/src/cg.jl#L70-L121) version of the code. I was expecting this code to be what is implemented and could not understand the discrepancy between the code I was seeing and the behavior. 

Thanks a lot for all what comes next. I will have to digest it. For now all what I can say is that if I naively copy-paste your commands, I get
```
ERROR: syntax: extra token "MyPreconditionerType" after end of expression
```
and that I'm still worried that since `Pl` was not a recognized keyword, I will get an error in the end no matter what. I'll continue experimenting.

**Comment by haampie** [comment]
Whoops, there was one bracket too much in the example, but that's fixed now. Give it another try ;)

Thanks for pointing out that the documentation is outdated. New documentation is already in the master branch, but for some reason the web page isn't updated automatically.

**Comment by randomjc** [comment]
Thanks! Right now I can't even compile
```
struct Foo
	bar
end
```
This gives me
```
ERROR: syntax: extra token "Foo" after end of expression
```
I'm sorry I'm struggling with so elementary stuff...

**Comment by haampie** [comment]
Ah, you might want to upgrade to Julia 0.6 then ;)

Op 26 aug. 2017 19:30 schreef "randomjc" <notifications@github.com>:

**Comment by randomjc** [comment]
Indeed I was using Julia 0.4.5 (this seems to be the default on Linux Mint 18.1). Everything seems to be working on Julia 0.6! Thanks again.
