### ISSUE TITLE
Documentation not updated

### ISSUE THREAD

**Issue by haampie** [JuliaMath/IterativeSolvers.jl#169]
I noticed that the new documentation is not published / deployed. Shouldn't it do so automatically when a new version is tagged in master?

**Comment by haampie** [comment]
@lopezm94, do you know more about this?

**Comment by lopezm94** [comment]
If I remember correctly I didn't add autodeploy at the moment of making the docs. [Here](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#SSH-Deploy-Keys-1) is the procedure though, you would need someone with access to the project settings to create repo access keys. Or it can be done manually by updating the `gh-pages` branch of this repo and using [JuliaDocs](https://github.com/JuliaDocs/Documenter.jl).

**Comment by andreasnoack** [comment]
I think we just figured out how to get this going.
