### ISSUE TITLE
Slow convergence of Chebyshev iteration 

### ISSUE THREAD

**Issue by jiahao** [JuliaMath/IterativeSolvers.jl#17]
I implemented the Chebyshev iteration algorithm from Linear Templates, but it's not clear to me why its convergence is so slow. The tests for it require an extremely large number of iterations to achieve minimal convergence, even when the exact range of eigenvalues are known.

It may be worth implementing a more sophisticated form of the Chebyshev iteration that takes higher order Chebyshev recurrences.

**Comment by lopezm94** [comment]
I don't know if this has anything to do, but shouldn't the 3rd and 4th argument be swapped? https://github.com/JuliaLang/IterativeSolvers.jl/blob/master/test/runtests.jl#L176

**Comment by haampie** [comment]
@andreasnoack: this issue can be closed. The problem was that the matrix in the tests had an eigenvalue very close to 0.
