### ISSUE TITLE
Remove plotting from this package

### ISSUE THREAD

**Issue by haampie** [JuliaMath/IterativeSolvers.jl#172]
I'm not sure what the general opinion is about this, but I feel the dependencies on `UnicodePlots` and `RecipesBase` are odd. 

Do we really need plotting? Considering you typically only plot the residual norm of each iteration, what's wrong with writing

```julia
using Plots
x, history = gmres(A, b, log = true)
plot(history[:resnorm], yscale = :log10)
```

Furthermore, plotting and `ConvergenceHistory` objects in general are not tested.

If we really want to have it, maybe it can be moved to another repository like IterativeSolversTools.jl as well.

**Comment by ChrisRackauckas** [comment]
I think the UnicodePlots dependency is a little odd, especially with the recipe already existing. But RecipesBase is essentially 1 macro and widely used. At this point I wouldn't consider it much of a dependency as much of a part of basic Julia.

**Comment by haampie** [comment]
Thanks @ChrisRackauckas, I think you're right
