### ISSUE TITLE
Broadcasting rather than BLAS 1 calls?

### ISSUE THREAD

**Issue by haampie** [JuliaMath/IterativeSolvers.jl#181]
There are some instances where BLAS calls can be replaced by broadcasting.

In CG and Chebyshev iteration there is an `axpby` which is currently written as `scale` and `axpy` (since `axpby` is not part of Julia 0.6). This looks wasteful:

```julia
scale!(cheb.u, β)
@blas! cheb.u += one(T) * cheb.c
```

could be replaced by

```julia
@. cheb.u = cheb.c + β * cheb.u
```

Is there any reason *not* to do this?  And while we're at it, can't we replace `axpy`'s with broadcasting in general?

cc'ing @andreasnoack because we probably discussed this earlier.

**Comment by andreasnoack** [comment]
I think that should work and probably faster since it is fused into a single traversal of the elements. As a matter of style, I prefer explicit dots over the `@.` macro.
