### ISSUE TITLE
Warning due to conflict

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaMath/IterativeSolvers.jl#188]
https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/240

Can this get a fix and a tag? It seems harmless but it's been around forever.

**Comment by haampie** [comment]
Yeah, agreed, not a good user experience. Not completely sure why the warning is triggered... It's not an exported type, and when I replace the references with `IterativeSolvers.Hessenberg` the warning persists.

**Comment by ChrisRackauckas** [comment]
Base.LinAlg exports `IterativeSolvers.Hessenberg` and it must be used before it's shadowed.

**Comment by haampie** [comment]
Thanks for reporting :)
