### ISSUE TITLE
Use correct tolerances on the solution vector in tests

### ISSUE THREAD

**Issue by jiahao** [JuliaMath/IterativeSolvers.jl#19]
The tests occasionally fail on random inputs. This is almost certainly due to not using the proper inequalities on the error bounds of the solution vector and/or residual vector. For many of these algorithms, these inequalities are known (or at least, for special cases), and we should use the known inequalities to test for correct convergence.

**Comment by haampie** [comment]
I think this is resolved since we're now using proper test problems with well-conditioned matrices.
