### ISSUE TITLE
Type instability in cg

### ISSUE THREAD

**Issue by mohamed82008** [JuliaMath/IterativeSolvers.jl#194]
https://github.com/JuliaMath/IterativeSolvers.jl/blob/756edef2b6a58a65b41f87127fbec1f8c62150c7/src/cg.jl#L203
The above line creates a type instability. Can be fixed by making `log::Type{Val{logging}}` and making `logging` a type parameter.

**Comment by andreasnoack** [comment]
Remember that we've constant propagation on 0.7 so I wouldn't use any `Val` for this.

**Comment by haampie** [comment]
Duplicate of #192
