### ISSUE TITLE
don't overtype

### ISSUE THREAD

**Issue by stevengj** [JuliaMath/IterativeSolvers.jl#2]
The arguments should not be `AbstractMatrix` types, since that implies access to the elements.   The argument should be untyped ("duck-typed"), and work for any type `T` supporting `*(A::T, v::AbstractVector)` and possibly `size(A::T)` (although for linear solvers this is not needed, since the size can be inferred from the right-hand-side vector).

**Comment by haampie** [comment]
This issue is also resolved by compatibility for LinearMaps

**Comment by Jutho** [comment]
:-). I didn't even remember this one. I guess this was before (and why) I started LinearMaps.jl
