### ISSUE TITLE
Docs for LOBPCG method missing

### ISSUE THREAD

**Issue by dkarrasch** [JuliaMath/IterativeSolvers.jl#211]
Scanning through the releases I realized that at version v0.6.0 another eigensolver named LOBPCG was introduced. Text searching the docs didn't yield a single hit. Would be nice to have a little bit of background and recommendations for usage etc.

**Comment by mohamed82008** [comment]
That's unfortunate. Is there any specific reason why Documenter.jl (or Literate.jl) was not used before to put the docstrings into the docs, just time limitation? I never used these before but I am sure you know they are quite popular, especially Documenter. I think Literate.jl can also add Jupyter notebooks to the docs.

**Comment by mohamed82008** [comment]
I think JuMP uses http://www.sphinx-doc.org/en/master/

**Comment by haampie** [comment]
Just add a page to https://github.com/JuliaMath/IterativeSolvers.jl/tree/master/docs/src and reference it in https://github.com/JuliaMath/IterativeSolvers.jl/blob/master/docs/make.jl, that's all.

**Comment by mohamed82008** [comment]
Close issue?
https://juliamath.github.io/IterativeSolvers.jl/latest/eigenproblems/lobpcg.html
