### ISSUE TITLE
Can `adjoint(A)` be placed outside of the loop?

### ISSUE THREAD

**Issue by vincentcp** [JuliaMath/IterativeSolvers.jl#240]
I have a linear object `A` that allocates some memory when creating the adjoint. 
When I apply `lsqr`, this adjoint is created in every iteration. 

Can `adjoint(A)` be placed outside of the loop?

**Comment by andreasnoack** [comment]
Yes. That should be possible. The best way to make this change happen is if you could prepare the PR. It should be a simple one.

**Comment by mschauer** [comment]
The author's of `lsqr` give a helpful comment:
```
            # Note that the following three lines are a band aid for a GEMM: X: C := αA'B + βC.
            # This is already supported in mul! for sparse and distributed matrices, but not yet dense
            mul!(tmpn, adjoint(A), u)
            v .= -beta .* v .+ tmpn
```

**Comment by andreasnoack** [comment]
> The author's of `lsqr` give a helpful comment:

I think I'm missing something. Why would that affect moving the call to`adjoint` outside the loop and save the result as e.g. `adjA`?

**Comment by vincentcp** [comment]
If `adjoint(A)` is an expensive operation why do I do need to do it every iteration while its result stays the same?

**Comment by mschauer** [comment]
One can certainly take the adjoint out of the loop.  The comment just points at the underlying problem.  You (@andreasnoack) wrote this 4 years ago. Maybe it is fixed by now?

**Comment by andreasnoack** [comment]
> Maybe it is fixed by now?

Unfortunate not, see https://github.com/JuliaLang/julia/issues/23919
