### ISSUE TITLE
Two Possibilities for Speedup in CG

### ISSUE THREAD

**Issue by lruthotto** [JuliaMath/IterativeSolvers.jl#26]
Hi there!

While playing around with our implementation of CG ( https://github.com/lruthotto/SimpleIterativeSolvers.jl ) we've discovered two possibilities for speeding up iterative methods for sparse matrices, I would like to share here.

1) in order to avoid allocation of large vectors we went over to use A_mul_B! directly. In our (limited) experience this can save around 10-15% computation time

2) When profiling our code we've found that  the following operations

```
x += alpha*p    # equivalent to: BLAS.axpy!(n,alpha,p,1,x,1) 
```

or

```
r -= alpha*Ap   # equivalent to: BLAS.axpy!(n,-alpha,Ap,1,r,1)
```

or

```
p = z + beta*p  # equivalent to  BLAS.axpy!(n,1.0,z,1,BLAS.scal!(n,beta,p,1),1)
```

take a lot of time. However, for some strange reason I could so far only replace the first one Otherwise I run into numerical instabilities. If anybody can explain them to me, I would be very happy.  Anyway, just replacing the first one gives another 10-15% speedup. 

I hope this remark is useful in improving the CG in this package. If you are interested in more detail, I put a small comparison of the CG implementations in our GIT repository (benchmark/benchmarkCG.jl)

Cheers,
Lars

**Comment by ChrisRackauckas** [comment]
Remember that BLAS only works on dense matrices of `Float64`. IterativeSolvers.jl should definitely strive to be compatible with a wider array of Julia-defined types than that. However, because of the way specialization works, there's not cost to having a branch like:

```julia
if eltype(x) <: Float64
  BLAS.axpy!(n,alpha,p,1,x,1) 
else
  x += alpha*p
end
```

since the conditional will compile away depending on the type information of `x`. 

But since this is done by SugarBLAS now, maybe @lopezm94 could have it do a type check like this inside the macro?

**Comment by ChrisRackauckas** [comment]
Ahh, thanks for clearing that up. Still, that's a very small set of numbers. Won't it all error on BigFloat, ArbFloat, DecFP, etc?

**Comment by andreasnoack** [comment]
No
```jl
julia> α, x, y = BigFloat(randn()), BigFloat.(randn(5)), BigFloat.(randn(5));

julia> LinAlg.axpy!(α, x, y)
5-element Array{BigFloat,1}:
 -7.994634116791716186538899681933872408079329717009533790024007878578966856952803e-01
  1.301872302490378346950038800158089411927933488017244955685243311275037236818264
 -5.992847575369260773427484928226179506729502915797758011228660003861037908201581e-01
 -1.307313646702618041105021222685954268815260987340107622452754855047786508581709
  2.761889634950335809904056368559058708437947327569207752449163730933817673118824e-01

julia> α, x, y = ArbFloat(randn()), ArbFloat.(randn(5)), ArbFloat.(randn(5));

julia> LinAlg.axpy!(α, x, y)
5-element Array{ArbFloats.ArbFloat,1}:
  0.5246082160341994892963865
 -1.206558649594778432414492
 -1.600857167315307230512769
 -1.317117928392613746495463
 -1.286536396824287771752109

julia> α, x, y = Dec32(randn()), Dec32.(randn(5)), Dec32.(randn(5));

julia> LinAlg.axpy!(α, x, y)
5-element Array{DecFP.Dec32,1}:
 -1780289E-6
 +4737067E-7
 +1174026E-6
 +9344190E-7
 -1400619E-6
```

**Comment by ChrisRackauckas** [comment]
But you said `axpy!` is completely generic. Is that true for all other LinAlg BLAS functions?

**Comment by andreasnoack** [comment]
That is a small number of functions. All the relevant BLAS functions for iterative solvers should have generic fallbacks so it should be possible to compose an iterative solver out of our linear algebra API and have it working on e.g. a `DMatrix{Quaternion{BigFloat},SparseMatrixCSC{Quaternion{BigFloat},Int}}` (haven't tested though)

**Comment by ChrisRackauckas** [comment]
Okay, good to know. I just didn't know that a good portion of Julia's BLAS functions had generic fallbacks.

Then is there anything left in this issue now that the SugarBLAS macros have merged?

**Comment by andreasnoack** [comment]
I'm not completely up to date on the code base here so we should hear @lopezm94.

**Comment by lopezm94** [comment]
It is good to close now. `SugarBLAS.blas!` was added wherever I saw possible.
