### ISSUE TITLE
What is the status of eigensolvers in this package?

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaMath/IterativeSolvers.jl#44]
I would like to use this package for eigenproblems. Which eigenfactorizations are working? Which are tested? I see a branch arpackgobyebye which looks like it has both ERAM and IRAM, but it hasn't been updated or merged since 2014.

**Comment by haampie** [comment]
Not much progress ever since unfortunately. My implementation of Jacobi-Davidson resides in a seperate package over here: https://github.com/haampie/JacobiDavidson.jl/

**Comment by jpfairbanks** [comment]
I ended up forking that branch and making it work for my needs. It served its purpose, but I don't have a pressing need to keep working on it.
