### ISSUE TITLE
Docs incorrect for `cg`

### ISSUE THREAD

**Issue by timholy** [JuliaMath/IterativeSolvers.jl#53]
From the README:

> All linear solvers have a common function declaration
> solver(A, b::Vector, [x, Pl, Pr, varargs...]; tol::Real, maxiter::Int, kwargs...)

`cg` starts from zero and doesn't take the `x` input---if you try to supply it, you get a cryptic error:

``` jl
julia> cg(A, rand(5), rand(5))
ERROR: DimensionMismatch("dot product arguments have lengths 5 and 1")
 in dot at linalg/blas.jl:153
 in dot at linalg/generic.jl:286
 in cg! at /home/tim/.julia/v0.4/IterativeSolvers/src/cg.jl:18
 in cg! at /home/tim/.julia/v0.4/IterativeSolvers/src/cg.jl:8
 in cg at /home/tim/.julia/v0.4/IterativeSolvers/src/cg.jl:3
```

Is starting at zero important for `cg`, or should one be able to supply `x`?

**Comment by dpo** [comment]
It's generally not a good idea to supply `x`. If you supply an `x` that is close to a solution, an iterative method is likely to compute small steps that will vanish (when you add x + ∆x) due to numerical cancellation. If you want to "start" from a nonzero `x`, it's typically better to shift your system Ax=b to A ∆x = r, where r = b-Ax, let CG solve A ∆x = r, and then to compute x + ∆x at the end.

**Comment by astudillor** [comment]
@dpo Could you point out any reference for that, please? I think supplying a nonzero initial guess for CG is a very common practice.

**Comment by dpo** [comment]
@astudillor I'm not sure there's a reference out there about it. It's nothing specific to CG but applies to all finite-precision computations. In a basic scientific computing class, you'll typically see the example of adding the first N terms of the alternating harmonic series (with N large), first in increasing, then in decreasing order. It's the same phenomenon. Here's a simplistic example in Julia (I'm sure there's a more efficient way to do this!) I use `Float16` to emphasize the effect:

```JULIA
julia> N = 10^8

# Forward
julia> app1 = Float16(0.0);
julia> for i = 1 : N
       app1 += Float16((-1)^(i+1) / i)
       end
julia> app1
Float16(0.6963)

# Backward
julia> app2 = Float16(0.0);
julia> for i = N : -1 : 1
       app2 += Float16((-1)^(i+1) / i)
       end
julia> app2
Float16(0.6934)

# The asymptotic sum is
julia> log(Float16(2.0))
Float16(0.6934)
```

**Comment by jpfairbanks** [comment]
@dpo How does the example you provided relate to CG? As far as I can tell the only thing it shows is that order matters when performing arithmetic on Floats.

**Comment by zimoun** [comment]
As all the Krylov method, it should be possible to provide an initial to `cg`.
Therefore, there is a kind of bug.

Now, from the algorithmic point of view, the question is: is it a good idea to "help" or not with an initial guess ?
There is literature, e.g., see Hegedüs trick.
Give a look at "5.8.3 The Backward Error Concept in Iterative Computations" from "Krylov Subspace Methods: Principles and Analysis" by Jörg Liesen and Zdenek Strakos.

What it is generally remarked is: the non-zero initial guess does not help for the convergence behavior.
