### ISSUE TITLE
GMRES docs need to explain macro- and microiterations better

### ISSUE THREAD

**Issue by dprn** [JuliaMath/IterativeSolvers.jl#60]
According to the docs, for every solver:
- `maxiter` is the maximum number of allowed iterations, which conventionally defaults to `length(b)`

However this is not true (at least for `gmres`). Indeed, the default number of iterations is 1, which obviously very rarely converge (from https://github.com/JuliaLang/IterativeSolvers.jl/blob/6ab23802336ec7883965c93c6ff23ca33a735e29/src/gmres.jl):

```
gmres(A, b, Pl=1, Pr=1;
      tol=sqrt(eps(typeof(real(b[1])))), maxiter::Int=1, restart::Int=min(20,length(b))) =
    gmres!(zerox(A,b), A, b, Pl, Pr; tol=tol, maxiter=maxiter, restart=restart)
```

**Comment by mschauer** [comment]
Not quite, but I agree it is a bit misleading. ``gmres`` wraps both the restarted and the not-restarted algorithm, ``restart`` gives the number of steps in the inner loop (restarted after), ``maxiter`` the number of outer loops. As ``restart=min(20,length(b))`` and ``maxiter=1`` the default arguments correspond to a not restarted gmres which runs for a total of ``restart*maxiter==min(20,length(b))`` iterations.

**Comment by mschauer** [comment]
With that, do you have an idea for better naming of the parameters?

**Comment by jiahao** [comment]
The standard terms AFAICT are macroiteration and  and microiteration. There is clearly a documentation issue at hand.

**Comment by zimoun** [comment]
From my knowledge, `maxiter` and `restart` are the "classical" names for these parameters. And still from my knowledge, we talk about inner-loop and outer-loop.

Should  modify `restart: Maximum number of inner iterations (GMRES(restart))`
And should add that the total number of iterations is therefore: `maxiter*restart`, and specify that the full `gmres` is `maxiter=1`.

I miss a point: the doc is it the commentary in the top of the function ? why is it not a docstring ?

**Comment by lopezm94** [comment]
For the new GMRES API we are thinking of defining maxiter as total number of iterations, i.e., ((outer-1)*inner + inner_left). The method will then calculate the number of outer iterations as ceil(maxiter/restart)
