### ISSUE TITLE
Integration with Plots.jl?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaMath/IterativeSolvers.jl#76]
I think it would be interesting to supply a recipe for the ConvergenceHistory type. This recipe would make it easy to plot the convergence history via `plot(ch)`. The only dependency would be `RecipesBase` which is really small, and recipe codes are usually short as well. It would be a small convenience change that could help the Julia ecosystem work more fluidly.

**Comment by lopezm94** [comment]
There is a working implementation of 2 recipes in #94 if you want to check it out.
